### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by chervbyn** [TahroO/SpaceInvader#1]
- [x] check space ship velocity (too slow)
- [x] check gun velocity (too fast)
- [ ] hide outs
- [ ] ground
- [x] alien bullets
- [x] player live
- [x] collision alien bullet <-> gun
- [ ] collision alien bullet <-> ground
- [ ] collision alien <-> gun
- [ ] collision alien <-> ground
- [ ] collision alien <-> hide out
- [ ] alien, spaceship status dying, nach Treffer
- [ ] hübsche grafiken
- [ ] high sorce

### Aliens
11 Spalten, 5 Reihen nehmen ca 70% Breite und 37% Höhe der Spielfläche ein.

https://www.youtube.com/watch?v=MU4psw3ccUI

@TahroO
